; ================================================================
;  PlatformIO — Robot Laberinto v6
; ================================================================
[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

lib_deps =
    knolleary/PubSubClient @ ^2.8

; -I include  →  expone include/ (config.h, globals.h) a todas las libs locales
build_flags =
    -I include
    -DCORE_DEBUG_LEVEL=3

; deep+  →  el LDF resuelve dependencias transitivas entre libs locales
lib_ldf_mode = deep+

monitor_speed = 115200
upload_speed  = 921600
